head.load(
    "/bitrix/templates/technocom/js/lib/jquery.js",
    "/bitrix/templates/technocom/js/jquery.selectric.min.js",
    "/bitrix/templates/technocom/js/durman.js",
    "/bitrix/templates/technocom/js/lib/cycle2.js",
    "/bitrix/templates/technocom/js/lib/cycle2.carousel.js",
    "/bitrix/templates/technocom/js/lib/jquery.mousewheel.js",
    "/bitrix/templates/technocom/js/common.js",
    "/bitrix/templates/technocom/js/lib/fancybox/jquery.fancybox.pack.js",
    "/bitrix/templates/technocom/js/lib/jquery.maskedinput.min.js",
    "/bitrix/templates/technocom/js/xipovski.js",
    "/bitrix/templates/technocom/js/scaling.js",
    "/bitrix/templates/technocom/js/scripts.js"
);
